### ISSUE TITLE
代码不完善吗？我看演示有一个streamlit，这个页面能提供吗？

### ISSUE THREAD

**Issue by yayaQAQ** [IDEA-FinAI/ToG#1]
好多bug呀。
<img width="1149" alt="image" src="https://github.com/IDEA-FinAI/ToG/assets/20497531/95d4323b-ad0e-4f1b-bdde-4a6b0f686e49">
<img width="1169" alt="image" src="https://github.com/IDEA-FinAI/ToG/assets/20497531/e4e28551-7ea5-4818-b623-42b153da3fd5">
<img width="833" alt="image" src="https://github.com/IDEA-FinAI/ToG/assets/20497531/d299a37c-23d1-49ff-b857-b131ac97cfb9">

**Comment by yayaQAQ** [comment]
<img width="1133" alt="image" src="https://github.com/IDEA-FinAI/ToG/assets/20497531/5846ef11-143e-4eb2-a754-bba1f90892e0">
我怎么感觉是你们随机修改了一些地方啊。。。怎么会有这种错误？

**Comment by GasolSun36** [comment]
Hi, 您好，请尝试最新的代码版本，您之前的版本是未更新的版本。

**Comment by soledad921** [comment]
> <img alt="image" width="1133" src="https://private-user-images.githubusercontent.com/20497531/287910586-5846ef11-143e-4eb2-a754-bba1f90892e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTIwMzMsIm5iZiI6MTcwMTkxMTczMywicGF0aCI6Ii8yMDQ5NzUzMS8yODc5MTA1ODYtNTg0NmVmMTEtMTQzZS00ZWIyLWE3NTQtYmJhMWY5MDg5MmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAxMTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNTk2ZDQzMTQ4MmNkNDY4YmQyMGViZmI3NWE1ODI3NmE3ZDIxMGJmNGI4YWIwYmE0ZTRmNDMzYWQ1ZTE4NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TurfyXzyZZgxY5SCyzQSrt73fki7CaHpVnwC5vi8FOM"> 我怎么感觉是你们随机修改了一些地方啊。。。怎么会有这种错误？

很抱歉，我们之前在代码管理上 出了些小问题。现在bug已经修复，在本地部署好KG服务后，是可以正常运行的。关于streamlit demo，我们将在之后的另一个项目中发布

**Comment by yayaQAQ** [comment]
> > <img alt="image" width="1133" src="https://private-user-images.githubusercontent.com/20497531/287910586-5846ef11-143e-4eb2-a754-bba1f90892e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTIwMzMsIm5iZiI6MTcwMTkxMTczMywicGF0aCI6Ii8yMDQ5NzUzMS8yODc5MTA1ODYtNTg0NmVmMTEtMTQzZS00ZWIyLWE3NTQtYmJhMWY5MDg5MmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAxMTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNTk2ZDQzMTQ4MmNkNDY4YmQyMGViZmI3NWE1ODI3NmE3ZDIxMGJmNGI4YWIwYmE0ZTRmNDMzYWQ1ZTE4NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TurfyXzyZZgxY5SCyzQSrt73fki7CaHpVnwC5vi8FOM"> 我怎么感觉是你们随机修改了一些地方啊。。。怎么会有这种错误？
> 
> 很抱歉，我们之前在代码管理上 出了些小问题。现在bug已经修复，在本地部署好KG服务后，是可以正常运行的。关于streamlit demo，我们将在之后的另一个项目中发布

好的，大概什么时候会发布呢？
