### ISSUE TITLE
Bug in eval of cwq

### ISSUE THREAD

**Issue by YaooXu** [IDEA-FinAI/ToG#10]
When I use the eval.py to evaluate the performance of ToG on CWQ, I encounter an error:
```bash
File "/data/KBQA/ToG-new/eval/utils.py", line 63, in align
    alias = answer['aliases']
TypeError: string indices must be integers
```
In the cwq.json, the 'answer' of each query is a string, and it has no 'aliases' key.

**Comment by GasolSun36** [comment]
Some data sets do not have aliases and can be removed directly.
