### ISSUE TITLE
About the missing entity name in Freebase database

### ISSUE THREAD

**Issue by zh-qifan** [IDEA-FinAI/ToG#16]
Hi,

I found that some extracted entities are "UnNamed Entity" because the corresponding (entity id, type.object.name, <entity name we want to extract>) is missing. May I ask how do you address this problem? I think this may greatly affect the accuracy of your algorithm.

Thank you!

**Comment by GasolSun36** [comment]
Hi,
We have discussed this issue in the paper, and we proposed ToG-R, which makes the algorithm focus on relations rather than intermediate entities.

**Comment by zh-qifan** [comment]
I see. Thank you for your answer!
