### ISSUE TITLE
prompt for linking topic entities to KG

### ISSUE THREAD

**Issue by alomrani** [IDEA-FinAI/ToG#2]
Hello, can you please provide prompt for finding the topic entities in the question? I need to use it for a new dataset. Thanks!

**Comment by YerayL** [comment]
+1

**Comment by GasolSun36** [comment]
Here is a simple 1-shot demonstration prompt for finding the topic entities, you may add more shot and more precise description (in this case, description is created by "Let's think step by step.") to improve the overall performance.

```
Please identify the entities in the given question.
Q: What sports team play in London did Drogba play for?
A: 1. London. It is the city in which the sports team for which Drogba played is located.
2. Drogba. This is the individual who played for the sports team. Knowledge about Drogba, specifically his career and the teams he played for, is most crucial for answering this question.
```
