### ISSUE TITLE
How do I ensure that Freebase is installed correctly

### ISSUE THREAD

**Issue by willer-lu** [IDEA-FinAI/ToG#21]
What's the correct result after running the Test example?      
My result is  `{'head': {'link': [], 'vars': ['name3']}, 'results': {'distinct': False, 'ordered': True, 'bindings': []}}`.   
I think there is some mistake, but I follow the readme in the "Freebase" folder.

**Comment by GasolSun36** [comment]
Hi，
Can you open a issue in my repo? I will @ my colleague to answer your question.

**Comment by willer-lu** [comment]
> Hi， Can you open a issue in my repo? I will @ my colleague to answer your question.

Yes, but another question, could you please fix the current version of the `eval.py` file as is mentioned at [https://github.com/IDEA-FinAI/ToG/issues/12](url)

**Comment by GasolSun36** [comment]
sure，sorry about that， i currently working

**Comment by willer-lu** [comment]
> sure，sorry about that， i currently working

Thanks a lot

**Comment by willer-lu** [comment]
> Hi, sure，sorry about that， i currently working on some projects and too busy right now. I will fix the bug as soon as possible.

Sorry, if the files about eval are not updated in time, ToG's results may appear in our paper with a lower score than the original paper.
