### ISSUE TITLE
Question about the datasets

### ISSUE THREAD

**Issue by Icamd** [IDEA-FinAI/ToG#30]
Hi! Thank you for your work!

I ran the test example without installing the Freebase dataset and encountered an error at "results = sparql.query().convert()", which says: "{URLError} <urlopen error [Errno 111] Connection refused". When I run main_freebase.py, it also reports "urllib.error.URLError: <urlopen error [Errno 110] Connection timed out". Can this issue be resolved by installing the Freebase dataset, or is it caused by an internet connection error? Thank you!

Additionally, is it possible to avoid installing the dataset? My server doesn't have 400GB of RAM, making it very difficult for me to run the program. Projects like RoG (Reasoning on Graph) can run on WebQSP and CWQ with only a few hundred MBs of memory. Is it possible to run ToG with a single dataset (like WebQSP) with less memory consumption? Thank you!

**Comment by Icamd** [comment]
And what are "head_relations" and "tail_relations" represent? Is "head_relations"=="relations that point to this entity from neighboring entities" and "tail_relations"=="relations that point to neighboring entities from this entity"? Thank you!

**Comment by GasolSun36** [comment]
> Hi! Thank you for your work!
> 
> I ran the test example without installing the Freebase dataset and encountered an error at "results = sparql.query().convert()", which says: "{URLError} <urlopen error [Errno 111] Connection refused". When I run main_freebase.py, it also reports "urllib.error.URLError: <urlopen error [Errno 110] Connection timed out". Can this issue be resolved by installing the Freebase dataset, or is it caused by an internet connection error? Thank you!
> 
> Additionally, is it possible to avoid installing the dataset? My server doesn't have 400GB of RAM, making it very difficult for me to run the program. Projects like RoG (Reasoning on Graph) can run on WebQSP and CWQ with only a few hundred MBs of memory. Is it possible to run ToG with a single dataset (like WebQSP) with less memory consumption? Thank you!

You can refer to this issue: [https://github.com/GasolSun36/ToG/issues/20](https://github.com/GasolSun36/ToG/issues/20)

**Comment by Icamd** [comment]
> > Hi! Thank you for your work!
> > I ran the test example without installing the Freebase dataset and encountered an error at "results = sparql.query().convert()", which says: "{URLError} <urlopen error [Errno 111] Connection refused". When I run main_freebase.py, it also reports "urllib.error.URLError: <urlopen error [Errno 110] Connection timed out". Can this issue be resolved by installing the Freebase dataset, or is it caused by an internet connection error? Thank you!
> > Additionally, is it possible to avoid installing the dataset? My server doesn't have 400GB of RAM, making it very difficult for me to run the program. Projects like RoG (Reasoning on Graph) can run on WebQSP and CWQ with only a few hundred MBs of memory. Is it possible to run ToG with a single dataset (like WebQSP) with less memory consumption? Thank you!
> 
> You can refer to this issue: [GasolSun36/ToG#20](https://github.com/GasolSun36/ToG/issues/20)

Thank you! I have another question. In some dataset samples (like WebQSP), the answer entity is not included in the graph and cannot be extracted using the normal ToG process. However, CoT appears to have the knowledge to answer the question and provides the correct answer even when it is not present in the graph. How is the Hits@1 value calculated in this situation? Does it mean that even if the answer entity is not included in the graph, if CoT answers it correctly, the Hits@1 is still considered as 1? Also, is this computation process reported in the paper? Thank you!
