### ISSUE TITLE
Memory needed for wikidata server

### ISSUE THREAD

**Issue by alomrani** [IDEA-FinAI/ToG#5]
Hello,

After running the wikidata servers for each chunk, my server crashes due to running out of RAM. How much memory does each server consume?

Thanks,
Mohammad

**Comment by GasolSun36** [comment]
@SaizhuoWang Maybe you can help answer this question.😄

**Comment by SaizhuoWang** [comment]
Hi, thanks for your interest in our work.

Approximately, each chunk takes ~170G of memory and it is suggested to prepare ~1.5-2T total memory to run the server. In case this amount of memory is not available on a single server node, you may also try running different chunks at different nodes, and you just need to make sure that the client can access all these nodes.
