### ISSUE TITLE
IndexError in relation_search_prune

### ISSUE THREAD

**Issue by liyichen-cly** [IDEA-FinAI/ToG#6]
Hi! I have encountered the following problems multiple times while running the code. Could you please advise on how to solve these issues?
main_freebase.py, line 52, in <module>
    retrieve_relations_with_scores = relation_search_prune(entity, topic_entity[entity], pre_relations, pre_heads[i], question, args)  # best entity triplet, entitiy_id
IndexError: list index out of range

**Comment by GasolSun36** [comment]
Can you provide specific examples of which data set causes this error?

**Comment by liyichen-cly** [comment]
Thank you for your reply! It often occurs in the CWQ dataset. When I repeat the process, the error disappears and it may randomly occur again next time.

**Comment by GasolSun36** [comment]
I think it may be that chatgpt mistakenly generated non-existent relations names during prune (hallucination issue). If you meet next time, please provide the specific data set and specific data ID.
